<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="com.functional.tests.Product_Functional_11_20">
        <methods>
          <include name="afterSuite"/>
          <include name="tearDown"/>
          <include name="beforeSuite"/>
          <include name="setUp"/>
          <include name="verifyProductFunctional_11_20" invocation-numbers="0"/>
        </methods>
      </class> <!-- com.functional.tests.Product_Functional_11_20 -->
      <class name="com.functional.tests.Product_Functional_21_33">
        <methods>
          <include name="verifyProductFunctional_21_33" invocation-numbers="0"/>
          <include name="afterSuite"/>
          <include name="tearDown"/>
          <include name="beforeSuite"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.functional.tests.Product_Functional_21_33 -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
