<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-LK1GIISB" failures="3" tests="35" name="com.functional.tests.TestCasesPageDetailedTestSuite" time="254.914" errors="0" timestamp="2025-09-04T13:18:20 IST" skipped="0">
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC01_RegisterUser" time="13.180"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC02_LoginCorrect" time="6.846"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC03_LoginIncorrect" time="7.777"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC04_LogoutUser" time="7.915"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC05_RegisterExisting" time="6.027"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC06_ContactUsForm" time="5.164"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC07_VerifyTestCasesPage" time="5.489"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC08_AllProductsDetail" time="8.057"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC09_SearchProduct" time="8.486"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC10_SubscriptionHome" time="6.555"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC11_SubscriptionCart" time="6.747"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC12_AddProductsInCart" time="11.711"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC13_VerifyQtyInCart" time="5.520"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC14_PlaceOrderRegisterWhile" time="6.204"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC15_PlaceOrderRegisterBefore" time="5.396"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC16_PlaceOrderLoginBefore" time="5.878"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC17_RemoveProductsFromCart" time="25.940"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC18_ViewCategoryProducts" time="4.556"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC19_ViewAndCartBrandProducts" time="4.577"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC20_SearchProductsVerifyCartAfterLogin" time="4.629"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC21_AddReviewOnProduct" time="4.706"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC22_AddToCartFromRecommended" time="4.538"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC23_VerifyAddressInCheckout" time="5.571"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC24_DownloadInvoiceAfterPurchase" time="6.670"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC25_ScrollUpUsingArrow" time="27.666"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC26_ScrollUpWithoutArrow" time="26.187"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC27_AllLinksCorrectScenarios" time="6.612"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC28_NoBrokenLinks" time="5.045"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC29_VerticalScrollSupport" time="0.146"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC30_FeedbackMailtoLink" time="0.587"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC31_ValidEmailSubscription" time="0.573"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC32_InvalidEmailSubscription" time="0.623">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.functional.tests.TestCasesPageDetailedTestSuite.TC32_InvalidEmailSubscription(TestCasesPageDetailedTestSuite.java:278)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC32_InvalidEmailSubscription -->
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC33_BlankEmailSubscription" time="0.406"/>
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC34_DuplicateEmailSubscription" time="8.378">
    <failure message="BUG: Duplicate email subscription was allowed - no duplicate detection" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Duplicate email subscription was allowed - no duplicate detection
at org.testng.Assert.fail(Assert.java:111)
at com.functional.tests.TestCasesPageDetailedTestSuite.TC34_DuplicateEmailSubscription(TestCasesPageDetailedTestSuite.java:324)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC34_DuplicateEmailSubscription -->
  <testcase classname="com.functional.tests.TestCasesPageDetailedTestSuite" name="TC35_LongEmailSubscription" time="0.552">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.functional.tests.TestCasesPageDetailedTestSuite.TC35_LongEmailSubscription(TestCasesPageDetailedTestSuite.java:343)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC35_LongEmailSubscription -->
</testsuite> <!-- com.functional.tests.TestCasesPageDetailedTestSuite -->
