<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-LK1GIISB" failures="5" tests="24" name="com.functional.tests.LoginTestSuite" time="248.600" errors="0" timestamp="2025-09-04T16:44:35 IST" skipped="0">
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_001_ValidCredentials" time="19.239"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_002_InvalidCredentials" time="7.518"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_003_BlankEmailField" time="4.823"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_004_BlankPasswordField" time="4.432"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_005_BothFieldsBlank" time="3.769"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_006_PasswordFieldMasked" time="2.280"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_007_ValidEmailWrongPassword" time="5.072"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_008_InvalidEmailRightPassword" time="5.862"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_009_ErrorMessageDisappears" time="11.291"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_010_EmailFormatValidation" time="9.024"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_011_MaximumLengthValidation" time="7.683">
    <failure message="EXPECTED FAIL: Long email/password (&gt;100 chars) should show error but was accepted - length validation is missing" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: EXPECTED FAIL: Long email/password (>100 chars) should show error but was accepted - length validation is missing
at org.testng.Assert.fail(Assert.java:111)
at com.functional.tests.LoginTestSuite.TC_ECOM_Login_011_MaximumLengthValidation(LoginTestSuite.java:480)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_ECOM_Login_011_MaximumLengthValidation -->
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_012_MixedCaseEmail" time="6.853">
    <failure message="EXPECTED TO PASS BUT FAILED: Mixed case email should work but was rejected" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: EXPECTED TO PASS BUT FAILED: Mixed case email should work but was rejected
at org.testng.Assert.fail(Assert.java:111)
at com.functional.tests.LoginTestSuite.TC_ECOM_Login_012_MixedCaseEmail(LoginTestSuite.java:523)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_ECOM_Login_012_MixedCaseEmail -->
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_013_RedirectToHomePage" time="12.879"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_014_InvalidCredentialsError" time="6.197"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_015_AccountDeletion" time="14.773"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_016_DeletedAccountLogin" time="8.444"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_017_PasswordCaseSensitivity" time="6.430"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_018_BrowserBackAfterLogout" time="26.863">
    <failure message="Logout button not found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Logout button not found
at org.testng.Assert.fail(Assert.java:111)
at com.functional.tests.LoginTestSuite.TC_ECOM_Login_018_BrowserBackAfterLogout(LoginTestSuite.java:795)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_ECOM_Login_018_BrowserBackAfterLogout -->
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_019_RedirectToLastVisitedPage" time="10.666">
    <failure message="BUG: User not redirected to last visited page after login" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: User not redirected to last visited page after login
at org.testng.Assert.fail(Assert.java:111)
at com.functional.tests.LoginTestSuite.TC_ECOM_Login_019_RedirectToLastVisitedPage(LoginTestSuite.java:830)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_ECOM_Login_019_RedirectToLastVisitedPage -->
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_020_SessionPersistence" time="22.766">
    <failure message="FAIL: Session did not persist across browser restart. Note: This might be expected behavior for security reasons." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: FAIL: Session did not persist across browser restart. Note: This might be expected behavior for security reasons.
at org.testng.Assert.fail(Assert.java:111)
at com.functional.tests.LoginTestSuite.TC_ECOM_Login_020_SessionPersistence(LoginTestSuite.java:915)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_ECOM_Login_020_SessionPersistence -->
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_021_VerifySuccessfulLogoutOperation" time="15.220"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_022_VerifyLogoutButtonNotVisibleWhenLoggedOut" time="12.215"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_023_VerifyLogoutButtonRapidClicks" time="9.851"/>
  <testcase classname="com.functional.tests.LoginTestSuite" name="TC_ECOM_Login_024_LoginPromptAfterLogout" time="14.450"/>
</testsuite> <!-- com.functional.tests.LoginTestSuite -->
